### ISSUE TITLE
v1.0.0

### ISSUE THREAD

**Issue by jamesplease** [jamesplease/materialish#63]
- [x] Ensure Button is 👌 
- [x] Ship CSS with build #50 
- [x] Document CSS API #24 
- [x] Finish new docs site ~~#46~~ , ~~#65~~
- [x] Write docs for new Button
- [x] Host site

**Comment by jamesplease** [comment]
These are done, so I am going to close this out. We're going to wait a bit before v1 though.

**Comment by jamesplease** [comment]
Reopening. @JPorry , what do you think? Are we ready for v1, or is there something else you would like to see before then?

One slightly-annoying thing is that once we cut v1, the versions will shoot up as any breaking change will require a major bump, and due to the nature of this lib, most changes will be breaking.

**Comment by jamesplease** [comment]
We chatted a little bit more. @JPorry is good with v1 after #208 gets merged, as well as the Lists component (#174 ).

**Comment by jamesplease** [comment]
Closing, as this hasn't really been tracking the current v1 plan. Once List gets added, we'll release v1.
